CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    recipient_id BIGINT NOT NULL REFERENCES users(id),
    type VARCHAR(40) NOT NULL,
    ride_id BIGINT NOT NULL REFERENCES rides(id),
    booking_id BIGINT REFERENCES bookings(id),
    actor_name VARCHAR(255),
    origin VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    requested_seats INTEGER,
    created_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP
);

CREATE INDEX idx_notifications_recipient_created
    ON notifications (recipient_id, created_at DESC, id DESC);

CREATE INDEX idx_notifications_recipient_unread
    ON notifications (recipient_id, created_at DESC)
    WHERE read_at IS NULL;

CREATE TABLE notification_outbox (
    id UUID PRIMARY KEY,
    payload TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP
);

CREATE INDEX idx_notification_outbox_pending
    ON notification_outbox (created_at, id)
    WHERE published_at IS NULL;
