spring:
  application:
    name: campusride

  datasource:
    url: jdbc:postgresql://localhost:5432/campusride
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: temporary-dev-secret-change-later
  expiration: 86400000